# Generated by Django 2.1.2 on 2018-11-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('chave', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='computadorstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.FloatField()),
                ('ram', models.FloatField()),
                ('id_pc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.computador')),
            ],
        ),
        migrations.CreateModel(
            name='pilhaprocessos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_processo', models.IntegerField()),
                ('id_computador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.computador')),
            ],
        ),
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='tarefapalavras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50)),
                ('id_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='pilhaprocessos',
            name='id_tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.tarefa'),
        ),
    ]
