# Generated by Django 2.1.2 on 2018-11-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('chave', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='computadorStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processador', models.FloatField()),
                ('ram', models.FloatField()),
                ('id_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.computador')),
            ],
        ),
        migrations.CreateModel(
            name='pilhaProcessos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_processo', models.BooleanField(default=True)),
                ('id_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.computador')),
            ],
        ),
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='tarefaPalavras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('palavra', models.CharField(max_length=50)),
                ('id_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='pilhaprocessos',
            name='id_tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tarefa'),
        ),
    ]
