# Generated by Django 2.1.2 on 2018-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilhaprocessos',
            name='id_computador',
        ),
    ]
