# Generated by Django 2.1.2 on 2018-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_remove_pilhaprocessos_id_computador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefapalavras',
            name='vezes',
            field=models.IntegerField(default=0),
        ),
    ]
