# Generated by Django 2.1.2 on 2018-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_tarefapalavras_vezes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilhaprocessos',
            name='tempo',
            field=models.FloatField(default=0.0),
        ),
    ]
